default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: blog_user


development:
  <<: *default
  database: blog_dev



test:
  <<: *default
  database: blog_test


production:
  <<: *default
  database: blog_prod
  password: <%= ENV['BLOG_DATABASE_PASSWORD'] %>
